clear; clc; close all;

addpath(genpath(pwd));

cfg = config_rmsc_local_refine();
set_random_seed(cfg.seed);

if ~exist(cfg.results_dir, 'dir')
    mkdir(cfg.results_dir);
end

csv_dir = fullfile(cfg.results_dir, 'csv');
if ~exist(csv_dir, 'dir')
    mkdir(csv_dir);
end

all_refine_results = struct();
best_rows = {};

for i = 1:size(cfg.network_list, 1)
    net_name  = cfg.network_list{i, 1};
    file_path = cfg.network_list{i, 2};

    fprintf('\n========================================\n');
    fprintf('Local RMSC refine for network: %s\n', net_name);
    fprintf('========================================\n');

    [A_full, A_lcc] = load_realworld_network(file_path, net_name); 
    A = A_lcc;

    coarse_best = cfg.coarse_best_params.(net_name);

    [numSeeds_list, Pc_list] = build_local_param_grid( ...
        coarse_best.numSeeds, coarse_best.Pc, cfg);

    refine_result = refine_rmsc_for_one_network(A, net_name, ...
        numSeeds_list, Pc_list, cfg);

    all_refine_results.(net_name) = refine_result;

    writetable(refine_result.scan_table, ...
        fullfile(csv_dir, sprintf('rmsc_local_refine_%s.csv', lower(net_name))));

    best_rows(end+1, :) = { ...
        net_name, ...
        coarse_best.numSeeds, ...
        coarse_best.Pc, ...
        refine_result.best_numSeeds, ...
        refine_result.best_Pc, ...
        refine_result.best_score, ...
        refine_result.best_metrics.ks_degree, ...
        refine_result.best_metrics.ks_clustering, ...
        refine_result.best_metrics.spearman_degree, ...
        refine_result.best_metrics.spearman_closeness, ...
        refine_result.best_metrics.spearman_betweenness, ...
        refine_result.best_metrics.actual_ratio_mean ...
        }; 
end

save(fullfile(cfg.results_dir, 'rmsc_local_refine_results.mat'), ...
    'all_refine_results', '-v7.3');

best_table = cell2table(best_rows, 'VariableNames', { ...
    'Network', ...
    'Coarse_numSeeds', 'Coarse_Pc', ...
    'Refined_numSeeds', 'Refined_Pc', 'Refined_Score', ...
    'KS_Degree', 'KS_Clustering', ...
    'Spearman_Degree', 'Spearman_Closeness', 'Spearman_Betweenness', ...
    'ActualRatioMean'});

disp(best_table);
writetable(best_table, fullfile(csv_dir, 'rmsc_local_refine_best_params.csv'));

fprintf('\nLocal RMSC refinement finished.\n');
fprintf('Saved to: %s\n', fullfile(csv_dir, 'rmsc_local_refine_best_params.csv'));