function score = compute_rmsc_score(metrics, cfg)

% KS 越小越好 -> 取负号
% Spearman 越大越好 -> 直接加
score = ...
    - cfg.weight_ks_degree      * metrics.ks_degree ...
    - cfg.weight_ks_clustering  * metrics.ks_clustering ...
    + cfg.weight_spearman_degree      * metrics.spearman_degree ...
    + cfg.weight_spearman_closeness   * metrics.spearman_closeness ...
    + cfg.weight_spearman_betweenness * metrics.spearman_betweenness;

end